<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="/assets/css/style.css">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Document</title>
</head>
<body>
    <header>
        <div class="header-container">
            <img src="/assets/images/logo-portfolio.svg" alt="logo">
            <div class="nav-bar">
                <a class="light-dark-mode">A changer</a>
                <a class="connection">Se connecter</a>
            </div>
        </div>
    </header>

    <main>
        <?php include $content ?>
    </main>

    <footer>
    
    </footer>
</body>
</html>