<!-- Profile -->
<section class="profil">
    <h1>Qui suis-je</h1>
    <div class="profil-container">
        <div class="description">
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum Lorem ipsum dolor sit, amet consectetur adipisicing elit. Id sapiente vitae amet saepe voluptatibus culpa et eveniet facere. Deserunt ullam dolorum voluptatem officia minus maxime tempore esse molestias fugiat neque, corrupti facilis aperiam minima magni accusantium voluptate tenetur a, facere autem sunt commodi? Veritatis inventore, porro perferendis sapiente molestiae mollitia?.</p>

            <a href="#contact"class="contact-btn">Me contacter</a>
        </div>

        <div class="profil-image">
            <img src="./assets/images/logo-portfolio.svg" alt="profil">
        </div>
    </div>
</section>

<!-- Projets -->


<!-- Compétences -->


<!-- Contact -->
 <section class="contact" id="contact">
     <div class="contact-container">
        <h1>Me contacter</h1>
        <form action="" method="post">
            <label for="name">Votre nom :</label>
            <input type="text" name="name" placeholder="Nom">
            <label for="email">Votre email :</label>
            <input type="email" name="email" placeholder="Email">
            <label for="message">Votre message :</label>
            <textarea name="message" placeholder="Message"></textarea>
            <div class="form-button-container">
                <input class="form-button" type="submit" value="Envoyer">
            </div>
        </form>
    </div>
    <div class="cv">
        <btn href="./assets/documents/CV-Mathilde-Cotelle.pdf" download>Télécharger mon CV</a>
    </div>
 </section>