<!-- Profile -->
<section class="profil">
    <h1>Qui suis-je</h1>
    <div class="profil-container">
        <div class="description">
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum Lorem ipsum dolor sit, amet consectetur adipisicing elit. Id sapiente vitae amet saepe voluptatibus culpa et eveniet facere. Deserunt ullam dolorum voluptatem officia minus maxime tempore esse molestias fugiat neque, corrupti facilis aperiam minima magni accusantium voluptate tenetur a, facere autem sunt commodi? Veritatis inventore, porro perferendis sapiente molestiae mollitia?.</p>

            <btn href="#contact"class="contact-btn">Me contacter</btn>
        </div>

        <div class="profil-image">
            <img src="./assets/images/logo-portfolio.svg" alt="profil">
        </div>
    </div>
</section>

<!-- Projets -->


<!-- Compétences -->


<!-- Contact -->
 <section class="contact" id="contact">
    <h1>Me contacter</h1>
    <div class="contact-container">
        <form action="" method="post">
            <input type="text" name="name" placeholder="Nom">
            <input type="email" name="email" placeholder="Email">
            <textarea name="message" placeholder="Message"></textarea>
            <input type="submit" value="Envoyer">
        </form>
    </div>
    <div class="cv">
        <a href="./assets/documents/CV-Mathilde-Cotelle.pdf" download>Télécharger mon CV</a>
    </div>
 </section>